export const WOW_QUOTES: string[] = [
  'Un aventurero listo revisa su bitácora de misiones cada mañana.',
  'Las mazmorras más duras dan el mejor botín: sigue estudiando.',
  'Ningún héroe conquistó una incursión sin antes descansar en el campamento.',
  'Tu racha es tu arma más poderosa. No la rompas.',
  'Hasta el guerrero más fuerte necesita un temporizador de enfoque.',
  'Los apuntes son los verdaderos tomos de hechizos.',
  'Cada tarea completada es experiencia ganada.',
  'El conocimiento es el botín legendario que nadie te puede robar.',
  'Un buen aventurero organiza su inventario... y su calendario de exámenes.',
  'Incluso los héroes toman descansos cortos entre incursiones de estudio.',
  'La disciplina de hoy es la leyenda de mañana.',
  'Reúne a tu gremio de apuntes antes del examen final.',
  'Las misiones pendientes no se completan solas, aventurero.',
  'Sube de nivel tu conocimiento, una incursión a la vez.',
  'El camino a la maestría está lleno de mazmorras... digo, tareas.',
  'Un pergamino bien organizado vale más que mil hechizos improvisados.',
  'Descansa, aventurero: hasta los campeones necesitan maná.',
];
